import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'l10n/app_localizations.dart'; // generated by flutter gen-l10n
import 'providers/settings_provider.dart';
import 'router/app_router.dart';
import 'theme/app_theme.dart';

/// Root application widget.
///
/// Locale selection:
///   [languageProvider] drives [MaterialApp.locale] — when the user changes
///   language in SettingsScreen the provider is invalidated and the entire
///   widget tree rebuilds with the new locale. No app restart required.
class DoodHisaabApp extends ConsumerWidget {
  const DoodHisaabApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Fallback to 'en' while the async provider is loading or on error.
    final languageCode = ref.watch(languageProvider).valueOrNull ?? 'en';

    final themeModeCode = ref.watch(themeModeProvider).valueOrNull ?? 'system';
    final themeMode = switch (themeModeCode) {
      'light' => ThemeMode.light,
      'dark' => ThemeMode.dark,
      _ => ThemeMode.system,
    };

    return MaterialApp.router(
      title: 'DoodHisaab',
      debugShowCheckedModeBanner: false,
      theme: buildAppTheme(),
      darkTheme: buildDarkTheme(),
      themeMode: themeMode,

      routerConfig: router,

      localizationsDelegates: const [
        AppLocalizations.delegate,           // generated — app strings
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('pa'),
        Locale('hi'),
        Locale('ur'),
      ],
      locale: Locale(languageCode),
    );
  }
}
