import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/services/analytics_service.dart';
import 'l10n/app_localizations.dart'; // generated by flutter gen-l10n
import 'providers/settings_provider.dart';
import 'router/app_router.dart';
import 'services/back_guard_channel.dart';
import 'theme/app_theme.dart';

/// Root application widget.
///
/// Locale selection:
///   [languageProvider] drives [MaterialApp.locale] — when the user changes
///   language in SettingsScreen the provider is invalidated and the entire
///   widget tree rebuilds with the new locale. No app restart required.
class DoodHisaabApp extends ConsumerStatefulWidget {
  const DoodHisaabApp({super.key});

  @override
  ConsumerState<DoodHisaabApp> createState() => _DoodHisaabAppState();
}

class _DoodHisaabAppState extends ConsumerState<DoodHisaabApp>
    with WidgetsBindingObserver {
  late final VoidCallback _routeListener;
  String? _lastRoutePath;
  String? _lastScreenName;
  DateTime? _lastScreenEnteredAt;
  bool _appInBackground = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _routeListener = () {
      final route = router.routeInformationProvider.value.uri.toString();
      final path = Uri.tryParse(route)?.path ?? route;
      final screenName = _screenNameForRoute(path);
      final previousScreenName = _lastScreenName;

      if (_lastRoutePath == path && _lastScreenEnteredAt != null) {
        return;
      }

      _flushCurrentScreenTimeSpent(nextScreenName: screenName);

      _lastRoutePath = path;
      _lastScreenName = screenName;
      _lastScreenEnteredAt = DateTime.now();
      _appInBackground = false;
      _fireAndForget(
        BackGuardChannel.setCurrentRoute(path),
        'BackGuardChannel.setCurrentRoute',
      );
      _fireAndForget(
        AnalyticsService.instance.trackScreenView(
          screenName: screenName,
          routeName: path,
          screenClass: screenName,
          navigationSource: previousScreenName,
        ),
        'AnalyticsService.trackScreenView',
      );
    };
    router.routerDelegate.addListener(_routeListener);
    WidgetsBinding.instance.addPostFrameCallback((_) => _routeListener());
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _flushCurrentScreenTimeSpent();
    router.routerDelegate.removeListener(_routeListener);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        if (_appInBackground &&
            _lastScreenName != null &&
            _lastRoutePath != null &&
            _lastScreenEnteredAt == null) {
          _lastScreenEnteredAt = DateTime.now();
        }
        _appInBackground = false;
        break;
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
        _flushCurrentScreenTimeSpent();
        _appInBackground = true;
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    // Fallback to 'en' while the async provider is loading or on error.
    final languageCode = ref.watch(languageProvider).valueOrNull ?? 'en';

    final themeModeCode = ref.watch(themeModeProvider).valueOrNull ?? 'system';
    final themeMode = switch (themeModeCode) {
      'light' => ThemeMode.light,
      _ => ThemeMode.system,
    };

    return MaterialApp.router(
      title: 'DoodHisaab',
      debugShowCheckedModeBanner: false,
      theme: buildAppTheme(),
      darkTheme: buildAppTheme(),
      themeMode: themeMode,
      routerConfig: router,
      localizationsDelegates: const [
        AppLocalizations.delegate, // generated — app strings
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      locale: Locale(languageCode),
    );
  }

  void _fireAndForget(Future<void> task, String label) {
    unawaited(
      task.catchError((Object error, StackTrace stack) {
        debugPrint('$label failed: $error');
        debugPrintStack(stackTrace: stack);
      }),
    );
  }

  void _flushCurrentScreenTimeSpent({String? nextScreenName}) {
    if (_lastRoutePath == null ||
        _lastScreenName == null ||
        _lastScreenEnteredAt == null) {
      return;
    }

    final durationMs =
        DateTime.now().difference(_lastScreenEnteredAt!).inMilliseconds;
    _lastScreenEnteredAt = null;

    if (durationMs < 150) return;

    _fireAndForget(
      AnalyticsService.instance.trackTimeSpent(
        screenName: _lastScreenName!,
        routeName: _lastRoutePath!,
        durationMs: durationMs,
        nextScreenName: nextScreenName,
      ),
      'AnalyticsService.trackTimeSpent',
    );
  }
}

String _screenNameForRoute(String route) {
  final path = Uri.tryParse(route)?.path ?? route;

  if (path == '/lock') return 'Lock';
  if (path == '/home') return 'Home';
  if (path == '/onboarding') return 'Onboarding';
  if (path == '/delivery/entry') return 'Delivery Entry';
  if (path == '/payment/entry') return 'Payment Entry';
  if (path == '/customers') return 'Customers List';
  if (path == '/customers/new') return 'Add/Edit Customer';
  if (path == '/customers/reorder') return 'Route Reorder';
  if (path.startsWith('/customers/')) return 'Customer Profile';
  if (path == '/reports') return 'Reports';
  if (path.startsWith('/reports/statement/')) return 'Customer Statement';
  if (path == '/expenses/new') return 'Expense Entry';
  if (path == '/income/new') return 'Other Income Entry';
  if (path == '/settings') return 'Settings';
  if (path == '/settings/price') return 'Price Settings';
  if (path == '/settings/backup') return 'Backup';
  if (path == '/settings/export') return 'Export';
  if (path == '/settings/calculator') return 'Calculator';
  if (path == '/tutorial') return 'Tutorial';
  if (path == '/privacy') return 'Privacy';
  return 'Unknown';
}
